version: '3.7'

services:
  mysql-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'nutOps_database'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'cN4AKvtgJfbsk69T'
      MYSQL_ROOT_PASSWORD: 'cN4AKvtgJfbsk69T'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  app:
    build: .
    container_name: nutOps
    environment:
      - DATABASE_URL=mysql://root:cN4AKvtgJfbsk69T@mysql-db:3306/nutOps_database
    ports:
      - 3030:3030
    volumes:
      - .:/usr/app
    links:
      - mysql-db
    depends_on:
      - mysql-db
volumes:
  my-db: ~
